improve color handling and debug messaging

diff --git a/sysz b/sysz
--- a/sysz
+++ b/sysz
@@ -126,21 +126,27 @@ EOF
 }
 
 _sysz_quit() {
+  _sysz_debug "exit: $1"
   [[ $DEBUG = true ]] && cat sysz.debug >&2
   exit "$1"
 }
 
+red() {
+  if [[ $SYSZ_COLOR = 1 ]]; then
+    echo -e "$RED$*$RESET"
+  else
+    echo "$*"
+  fi
+}
+
 _sysz_error() {
-  echo "ERROR: $*" >&2
+  _sysz_debug "ERROR: $*"
+  red "ERROR: $*" >&2
   _sysz_quit 1
 }
 
 _sysz_debug() {
-  [[ $DEBUG = true ]] && echo "$(date -Isec) $*" >>sysz.debug
-}
-_sysz_run() {
-  _sysz_debug "> $*"
-  "$@" || _sysz_error "Failed: $*"
+  [[ $DEBUG = true ]] && echo "$(date -Isec) '$*'" >>sysz.debug
 }
 
 _sysz_ctl() {
@@ -150,7 +156,10 @@ _sysz_ctl() {
 
 _sysz_verbose() {
   [[ $VERBOSE = true ]] && echo '>' "$@" >&2
-  _sysz_run "$@"
+  _sysz_debug "> $*"
+  SYSTEMD_COLORS=$SYSZ_COLOR "$@"
+  code=$?
+  [[ $VERBOSE = true && $code != 0 ]] && red "ERROR: Failed: $*" >&2
 }
 
 _sysz_systemctl() {
@@ -215,10 +224,17 @@ _sysz_show() {
   _sysz_ctl "$(_sysz_mgr "$1")" show "${1##* }" -p "$2" --value
 }
 
-_sysz_color_line() {
+_sysz_color_unit() {
   local color
-  color=$1
-  sed -Ee 's,^(\[[us]\] )?([^ ]+) [^ ]+ [^ ]+( [^ ]+)?( .*)?$,\1'"$color"'\2'"$RESET"'\4,'
+  local reset
+  if [[ $SYSZ_COLOR = 1 ]]; then
+    color=$1
+    reset=$RESET
+  else
+    color=
+    reset=
+  fi
+  sed -Ee 's,^(\[[us]\] )?([^ ]+) [^ ]+ [^ ]+( [^ ]+)?( .*)?$,\1'"$color"'\2'"$reset"'\4,'
 }
 
 _sysz_ls() {
@@ -259,7 +275,7 @@ _sysz_ls() {
       "$@" |
       grep -Ev '^\S+\s+(\S+\s+)?('"$filter"')' |
       sed -Ee 's/ +/ /g;' |
-      _sysz_color_line "$color" |
+      _sysz_color_unit "$color" |
       sed -e "s/^/[${mgr:0:1}] /"
   done
 }
@@ -550,7 +566,7 @@ _sysz_daemon_reload_prompt() {
   _sysz_debug "daemon-reload: ${managers[*]}"
 
   for mgr in "${managers[@]}"; do
-    _sysz_systemctl "$(_sysz_mgr "$mgr")" daemon-reload >&2
+    _sysz_systemctl "$(_sysz_mgr "$mgr")" daemon-reload >&2 || error "daemon-reload failed"
   done
 }
 
@@ -833,8 +849,7 @@ for pick in "${picks[@]}"; do
       _sysz_quit $?
       ;;
     status)
-      # shellcheck disable=2086
-      SYSTEMD_COLORS=$SYSZ_COLOR _sysz_systemctl "$mgr" $cmd --no-pager "${ARGS[@]}" -- "$unit"
+      _sysz_systemctl "$mgr" "$cmd" --no-pager "${ARGS[@]}" -- "$unit"
       _sysz_quit $?
       ;;
     cat | show)
@@ -844,7 +859,7 @@ for pick in "${picks[@]}"; do
     *)
       _sysz_systemctl "$mgr" "$cmd" "${ARGS[@]}" -- "$unit"
       code=$?
-      SYSTEMD_COLORS=$SYSZ_COLOR _sysz_systemctl "$mgr" status --no-pager -- "$unit"
+      _sysz_systemctl "$mgr" status --no-pager -- "$unit"
       if [[ ${#picks[@]} -eq 1 ]]; then
         _sysz_quit "$code"
       fi
