Lazy load units
Much faster and removes the stupid sorting logic

Fixes #24

diff --git a/sysz b/sysz
--- a/sysz
+++ b/sysz
@@ -164,71 +164,69 @@ _sysz_show() {
   _sysz_systemctl "$manager" show "$unit" -p "$2" --value
 }
 
-_sysz_sort() {
-  local str
+_sysz_ls_args=(
+  --legend=false
+  --full
+  --plain
+  --no-pager
+)
+
+_sysz_ls() {
   local mgr
-  local unit
-  local n
-  while IFS= read -r str; do
-    mgr=${str%% *}
-    unit_colored=${str##* }
-    unit=${unit_colored//$'\e'[\[(]*([0-9;])[@-n]/}
+  local color
+  local color_code
+  mgr=$1
+  shift
+  color=$1
+  shift
 
-    if [[ $unit =~ \.service$ ]]; then
-      n=0
-      [[ $mgr = "[system]" ]] && n=1
-    elif [[ $unit =~ \.timer$ ]]; then
-      n=2
-      [[ $mgr = "[system]" ]] && n=3
-    elif [[ $unit =~ \.socket$ ]]; then
-      n=4
-      [[ $mgr = "[system]" ]] && n=5
-    elif [[ $mgr = "[user]" ]]; then
-      n=6
-    else
-      # then the rest based on file extension
-      n=7
-    fi
-    type=${unit##*.}
-    unit_undashed=${unit//-/}
-    echo "$n$type$unit_undashed $mgr $unit_colored"
-  done | sort -bifu | cut -d' ' -f2-
+  reset=$'\e[0m'
+  case $color in
+  green)
+    color_code=$'\e[32m'
+    ;;
+  yellow)
+    color_code=$'\e[33m'
+    ;;
+  red)
+    color_code=$'\e[31m'
+    ;;
+  none)
+    color_code=$reset
+    ;;
+  *)
+    echo "ERROR: Unknown color: $color" >&2
+    exit 1
+    ;;
+  esac
+
+  systemctl "--$mgr" list-units \
+    "${_sysz_ls_args[@]}" \
+    "$@" |
+    cut -f1 -d' ' |
+    sed -e "s/^/$color_code/;s/\$/$reset/" |
+    sed -e "s/^/[$mgr] /"
 }
 
-_sysz_list() {
-  local args
-  declare -a args
-  args=(
-    --all
-    --no-legend
-    --full
-    --plain
-    --no-pager
-    "${STATES[@]}"
-    "$@"
-  )
-  (
-    systemctl list-units "${args[@]}"
-    systemctl list-unit-files "${args[@]}"
-  ) | sort -u -t ' ' -k1,1 |
-    while read -r line; do
-      unit=${line%% *}
-      if [[ $line = *" active "* ]]; then
-        printf '\033[0;32m%s\033[0m\n' "$unit" # green
-      elif [[ $line = *" failed "* ]]; then
-        printf '\033[0;31m%s\033[0m\n' "$unit" # red
-      elif [[ $line = *" not-found "* ]]; then
-        printf '\033[1;33m%s\033[0m\n' "$unit" # red
-      else
-        echo "$unit"
-      fi
-    done
-}
+_sysz_units() {
+  for mgr in "${MANAGERS[@]}"; do
+    _sysz_ls "$mgr" red --state=failed --type=service
+    _sysz_ls "$mgr" red --state=failed --type=timer
+  done
 
-_sysz_list_units() {
-  for MANAGER in "${MANAGERS[@]}"; do
-    _sysz_list "--$MANAGER" | sed -e "s/^/[$MANAGER] /"
-  done | _sysz_sort
+  for mgr in "${MANAGERS[@]}"; do
+    _sysz_ls "$mgr" green --state=active --type=service
+    _sysz_ls "$mgr" green --state=active --type=timer
+    _sysz_ls "$mgr" yellow --state=not-found
+  done
+
+  for mgr in "${MANAGERS[@]}"; do
+    _sysz_ls "$mgr" none --all | grep -Ev '( active| failed| not-found|\.service|\.timer)'
+    systemctl "--$mgr" list-unit-files "${_sysz_ls_args[@]}" '*@.*' |
+      cut -f1 -d' ' |
+      sed -e "s/^/[$mgr] /"
+  done
+
 }
 
 # main
@@ -241,7 +239,7 @@ if [[ "$(printf '%s\n' "$MIN_FZF" "$(fzf --version | cut -d' ' -f1)" | sort -V |
   exit 1
 fi
 
-# root doesn't have user units
+# root does not have user units
 if [[ $EUID -eq 0 ]]; then
   MANAGERS=(system)
 else
@@ -300,10 +298,16 @@ while [[ -n $1 ]]; do
   _fzf_preview)
     shift
     _fzf_preview "$@"
+    exit 0
     ;;
   _fzf_cat)
     shift
     _fzf_cat "$@"
+    exit 0
+    ;;
+  _sysz_units)
+    _sysz_units
+    exit 0
     ;;
   h | help)
     _sysz_help
@@ -413,7 +417,7 @@ while :; do
   KEY=
 
   # prompt units
-  _sysz_list_units |
+  _sysz_units |
     fzf \
       --multi \
       --ansi \
