fix a bunch of stuff

diff --git a/sysz b/sysz
--- a/sysz
+++ b/sysz
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+set -f # disable globbing
 shopt -s lastpipe
 
 _sysz_help() {
@@ -7,16 +8,20 @@ _sysz_help() {
   cat >&2 <<EOF
 A utility for using systemctl interactively via fzf.
 
-Usage: $PROG [OPT] [CMD] [ARGS...]
+Usage: $PROG [OPTS...] [CMD] [ARGS...]
 
 Select multiple units using TAB
 
-Extra ARGS are passed to the systemctl command.
+Extra ARGS are passed to the systemctl command
+for each selected unit.
 
-OPT:
-  -u, --user             Only show --user services
-  -s, --sys, --system    Only show --user services
-  -a, --active           Only show active services
+sudo is automatically invoked if necessary.
+
+OPTS:
+  -u, --user             Only show --user units
+  -s, --sys, --system    Only show --user units
+  --state [STATE]        Only show units in STATE
+  -v, --verbose          Print the systemctl command
   -h, --help             Print this message
 
 If no option is given, both system and user units are shown.
@@ -24,7 +29,7 @@ If no option is given, both system and user units are shown.
 CMD:
   start                  systemctl start <unit>
   stop                   systemctl stop <unit>
-  re, restart            systemctl restart <unit>
+  r, restart             systemctl restart <unit>
   s, stat, status        systemctl status <unit>
   ed, edit               systemctl edit --full <unit>
   reload                 systemctl reload <unit>
@@ -41,11 +46,17 @@ environment variable SYSZ_HISTORY
 Default: $XDG_CACHE_HOME/sysz/history
 
 Examples:
-  $PROG --system stat      Get the status of a system unit
-  $PROG --user edit        Edit a user unit
-  $PROG start              Start a unit
-  $PROG -s -a stop         Stop an active system unit
-  $PROG -u s -n100         Show status of a user unit with 100 log lines.
+  $PROG -u                      User units
+  $PROG -s --state active       Active system units
+  $PROG --user --state failed   Failed user units
+
+Examples with commands:
+  $PROG start                     Start a unit
+  $PROG --sys s                   Get the status of a system unit
+  $PROG --user edit               Edit a user unit
+  $PROG s -n100                   Show 100 log lines of units
+  $PROG -s --state active stop    Stop an active system unit
+  $PROG --state failed r          Restart failed units
 EOF
 
   exit 1
@@ -82,7 +93,7 @@ _sysz_preview() {
     MANAGER=--system
     ;;
   *)
-    echo "ERROR: unknown manager: $PICK" >&2
+    echo "ERROR: unknown manager: $1" >&2
     exit 1
     ;;
   esac
@@ -92,20 +103,21 @@ _sysz_preview() {
 }
 
 _sysz_show() {
-  _sysz_systemctl "$1" show "$2" -p "$3" --value
-}
-
-_sysz_list_cmd() {
-  systemctl \
-    "$1" \
-    list-units \
-    --all \
-    --no-legend \
-    --full \
-    --no-pager \
-    $ACTIVE |
-    awk '{print $1}'
-
+  local MANAGER
+  case ${1%% *} in
+  '[user]')
+    MANAGER=--user
+    ;;
+  '[system]')
+    MANAGER=--system
+    ;;
+  *)
+    echo "ERROR: unknown manager: $PICK" >&2
+    exit 1
+    ;;
+  esac
+  UNIT=${1##* }
+  _sysz_systemctl $MANAGER show "$UNIT" -p "$2" --value
 }
 
 _sysz_sort() {
@@ -116,7 +128,7 @@ _sysz_sort() {
     elif [[ $string =~ \.service$ ]]; then
       # system services
       echo "1 $string"
-    elif [[ $string =~ \[user\].*\.timers$ ]]; then
+    elif [[ $string =~ \[user\].*\.timer$ ]]; then
       # user timers
       echo "2 $string"
     elif [[ $string =~ \.timer$ ]]; then
@@ -130,28 +142,48 @@ _sysz_sort() {
       echo "5 $string"
     elif [[ $string =~ \[user\] ]]; then
       # then user units based on file extenions
-      echo "7${string##*.} $string"
+      echo "6${string##*.} $string"
     else
       # then the rest based on file extension
-      echo "8${string##*.} $string"
+      echo "9${string##*.} $string"
     fi
   done | sort | cut -d' ' -f2-
 }
 
-_sysz_list() {
-  if [[ $UNITS = user || $UNITS = all ]]; then
-    _sysz_list_cmd --user | sed -e 's/^/[user] /'
-  fi
+_sysz_list_cmd() {
+  local ARGS
+  declare -a ARGS
+  ARGS=(
+    --all
+    --no-legend
+    --full
+    --plain
+    --no-pager
+    "${STATES[@]}"
+    "$@"
+  )
+  (
+    systemctl list-units "${ARGS[@]}"
+    systemctl list-unit-files "${ARGS[@]}"
+  ) | awk '{print $1}'
+}
 
-  if [[ $UNITS = system || $UNITS = all ]]; then
-    _sysz_list_cmd --system | sed -e 's/^/[system] /'
-  fi
+_sysz_list_units() {
+  (
+    if [[ $UNITS = user || $UNITS = all ]]; then
+      _sysz_list_cmd --user | sed -e 's/^/[user] /'
+    fi
+
+    if [[ $UNITS = system || $UNITS = all ]]; then
+      _sysz_list_cmd --system | sed -e 's/^/[system] /'
+    fi
+  ) | uniq | _sysz_sort
 }
 
 # main
 
 UNITS=all
-ACTIVE=
+declare -a STATES
 while [[ -n $1 ]]; do
   case $1 in
   -u | --user)
@@ -162,8 +194,9 @@ while [[ -n $1 ]]; do
     UNITS=system
     shift
     ;;
-  -a | --active)
-    ACTIVE="--state=active"
+  --state)
+    shift
+    STATES+=("--state=$1")
     shift
     ;;
   -v | --verbose)
@@ -179,7 +212,12 @@ while [[ -n $1 ]]; do
   esac
 done
 
-CMD=
+if [[ -n $STATE ]] && ! systemctl --state=help | grep -q "^$STATE "; then
+  echo "ERROR: unknown state: $STATE" >&2
+  exit 1
+fi
+
+declare CMD
 while :; do
   case $1 in
   _fzf_preview)
@@ -231,12 +269,12 @@ SYSZ_HISTORY=${SYSZ_HISTORY:-${XDG_CACHE_HOME:-~/.cache}/sysz/history}
 mkdir -p "$(dirname "$SYSZ_HISTORY")"
 touch "$SYSZ_HISTORY"
 
-declare -a PICKS
-_sysz_list |
-  _sysz_sort |
+_sysz_list_units |
   fzf \
     --multi \
     --ansi \
+    --reverse \
+    --no-sort \
     --history="$SYSZ_HISTORY" \
     --prompt="Units: " \
     --preview="'${BASH_SOURCE[0]}' _fzf_preview {}" |
@@ -252,27 +290,38 @@ declare -a CMDS
 if [[ -n $CMD ]]; then
   CMDS=("$CMD")
 else
+  if [[ ${#PICKS[@]} -eq 1 ]]; then
+    ACTIVE_STATE=$(_sysz_show "${PICKS[0]}" ActiveState)
+    UNIT_FILE_STATE=$(_sysz_show "${PICKS[0]}" UnitFileState)
+    CAN_RELOAD=$(_sysz_show "${PICKS[0]}" CanReload)
+    PREVIEW="'${BASH_SOURCE[0]}' _fzf_preview '${PICKS[0]}'"
+  else
+    PREVIEW="echo '$PICKS_STR'"
+    MULTI=true
+  fi
+
   fzf \
     --multi \
+    --ansi \
     --no-info \
     --reverse \
-    --ansi \
-    --preview="echo '$PICKS_STR'" \
+    --no-sort \
+    --preview="$PREVIEW" \
     --prompt="Commands: " \
     < <(
-      echo status
-      [[ $ACTIVE_STATE = active || ${#PICKS[@]} -gt 1 ]] && echo restart
-      [[ $ACTIVE_STATE != active || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;32m%s\033[0m\n' start
-      [[ $ACTIVE_STATE = active || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;31m%s\033[0m\n' stop
-      [[ $UNIT_FILE_STATE != enabled || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;32m%s\033[0m\n' enable
-      [[ $UNIT_FILE_STATE != enabled || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;32m%s\033[0m\n' 'enable --now'
-      [[ $UNIT_FILE_STATE = enabled || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;31m%s\033[0m\n' disable
-      [[ $UNIT_FILE_STATE = enabled || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;31m%s\033[0m\n' 'disable --now'
-      [[ $CAN_RELOAD = yes || ${#PICKS[@]} -gt 1 ]] && printf '\033[0;37m%s\033[0m\n' reload
-      echo cat
-      echo edit
-      echo journal
-      echo follow
+      echo status "${ARGS[*]}"
+      [[ $MULTI = true || $ACTIVE_STATE = active ]] && printf '\033[0;31m%s\033[0m %s\n' restart "${ARGS[*]}"
+      [[ $MULTI = true || $ACTIVE_STATE = inactive ]] && printf '\033[0;32m%s\033[0m %s\n' start "${ARGS[*]}"
+      [[ $MULTI = true || $ACTIVE_STATE = active ]] && printf '\033[0;31m%s\033[0m %s\n' stop "${ARGS[*]}"
+      [[ $MULTI = true || $UNIT_FILE_STATE = disabled ]] && printf '\033[0;32m%s\033[0m %s\n' "enable" "${ARGS[*]}"
+      [[ $MULTI = true || $UNIT_FILE_STATE = disabled ]] && printf '\033[0;32m%s\033[0m %s\n' "enable" "--now ${ARGS[*]}"
+      [[ $MULTI = true || $UNIT_FILE_STATE = enabled ]] && printf '\033[0;31m%s\033[0m %s\n' disable "${ARGS[*]}"
+      [[ $MULTI = true || $UNIT_FILE_STATE = enabled ]] && printf '\033[0;31m%s\033[0m %s\n' disable "--now ${ARGS[*]}"
+      [[ $MULTI = true || $CAN_RELOAD = yes ]] && printf '\033[0;37m%s\033[0m %s\n' reload "${ARGS[*]}"
+      echo cat "${ARGS[*]}"
+      echo edit "${ARGS[*]}"
+      echo journal "${ARGS[*]}"
+      echo follow "${ARGS[*]}"
     ) |
     readarray -t CMDS
 fi
@@ -296,17 +345,13 @@ for PICK in "${PICKS[@]}"; do
   esac
   UNIT=${PICK##* }
 
-  ACTIVE_STATE=$(_sysz_show $MANAGER "$UNIT" ActiveState)
-  UNIT_FILE_STATE=$(_sysz_show $MANAGER "$UNIT" UnitFileState)
-  CAN_RELOAD=$(_sysz_show $MANAGER "$UNIT" CanReload)
-
   for CMD in "${CMDS[@]}"; do
-    case $CMD in
+    case ${CMD%% *} in
     journal)
-      _sysz_journalctl $MANAGER -xe "--unit=$UNIT"
+      _sysz_journalctl $MANAGER -xe "--unit=$UNIT" "${ARGS[@]}"
       ;;
     follow)
-      _sysz_journalctl $MANAGER -xef "--unit=$UNIT"
+      _sysz_journalctl $MANAGER -xef "--unit=$UNIT" "${ARGS[@]}"
       ;;
     status)
       # shellcheck disable=2086
@@ -318,8 +363,11 @@ for PICK in "${PICKS[@]}"; do
       ;;
     *)
       # shellcheck disable=2086
-      _sysz_systemctl $MANAGER $CMD "$UNIT" "${ARGS[@]}"
+      _sysz_systemctl $MANAGER $CMD "$UNIT" "${ARGS[@]}" || CODE=$?
       _sysz_systemctl $MANAGER status "$UNIT" --no-pager
+      if [[ ${#PICKS[@]} -eq 1 ]]; then
+        exit $CODE
+      fi
       ;;
     esac
   done
