Fix state filtering

diff --git a/sysz b/sysz
--- a/sysz
+++ b/sysz
@@ -10,6 +10,7 @@ PROG=$(basename "$0")
 SYSZ_VERSION=1.4.3
 SYSZ_HISTORY=${SYSZ_HISTORY:-${XDG_CACHE_HOME:-~/.cache}/sysz/history}
 declare -a STATES
+declare -a TYPES
 
 _sysz_keys() {
   cat <<EOF
@@ -177,61 +178,83 @@ _sysz_ls_args=(
 )
 
 _sysz_ls() {
-  local mgr
-  local color
   local color_code
-  mgr=$1
-  shift
-  color=$1
-  shift
+  local state
+
+  for arg in "$@"; do
+    if [[ $arg = --state=* ]]; then
+      state=${arg#--state=} # strip --state=
+    fi
+  done
 
   reset=$'\e[0m'
-  case $color in
-  green)
-    color_code=$'\e[32m'
+  case $state in
+  active)
+    color_code=$'\e[32m' # green
     ;;
-  yellow)
-    color_code=$'\e[33m'
+  not-found)
+    color_code=$'\e[33m' # yellow
     ;;
-  red)
-    color_code=$'\e[31m'
-    ;;
-  none)
-    color_code=$reset
+  failed)
+    color_code=$'\e[31m' # red
     ;;
   *)
-    echo "ERROR: Unknown color: $color" >&2
-    exit 1
+    color_code=$reset
     ;;
   esac
 
-  systemctl "--$mgr" list-units \
-    "${_sysz_ls_args[@]}" \
-    "$@" |
-    cut -f1 -d' ' |
-    sed -e "s/^/$color_code/;s/\$/$reset/" |
-    sed -e "s/^/[$mgr] /"
+  for mgr in "${MANAGERS[@]}"; do
+    _sysz_systemctl "--$mgr" \
+      "${_sysz_ls_args[@]}" \
+      "$@" |
+      cut -f1 -d' ' |
+      sed -e "s/^/$color_code/;s/\$/$reset/" |
+      sed -e "s/^/[$mgr] /"
+  done
 }
 
 _sysz_units() {
-  for mgr in "${MANAGERS[@]}"; do
-    _sysz_ls "$mgr" red --state=failed --type=service
-    _sysz_ls "$mgr" red --state=failed --type=timer
+  local all_states
+  local all_types
+  local types
+  local states
+  local cmds
+
+  cmds=(list-units list-unit-files)
+  states=("${STATES[@]}")
+  if [[ ${#STATES[@]} -eq 0 ]]; then
+    states=(failed active)
+    cmds=(list-units)
+    all_states=true
+  fi
+
+  types=("${TYPES[@]}")
+  if [[ ${#TYPES[@]} -eq 0 ]]; then
+    types=(service timer)
+    all_types=true
+  fi
+
+  for cmd in "${cmds[@]}"; do
+    for state in "${states[@]}"; do
+      for unit_type in "${types[@]}"; do
+        _sysz_ls "$cmd" "--state=$state" "--type=$unit_type"
+      done
+
+      if [[ $all_types = true ]]; then
+        _sysz_ls "$cmd" "--state=$state" | grep -Ev '(\.service|\.timer)'
+      fi
+    done
+
+    if [[ $all_states = true ]]; then
+      _sysz_ls "$cmd" --state=not-found
+      _sysz_ls "$cmd" --all | grep -Ev '( active| failed| not-found|\.service|\.timer)'
+    fi
   done
 
-  for mgr in "${MANAGERS[@]}"; do
-    _sysz_ls "$mgr" green --state=active --type=service
-    _sysz_ls "$mgr" green --state=active --type=timer
-    _sysz_ls "$mgr" yellow --state=not-found
-  done
-
-  for mgr in "${MANAGERS[@]}"; do
-    _sysz_ls "$mgr" none --all | grep -Ev '( active| failed| not-found|\.service|\.timer)'
-    systemctl "--$mgr" list-unit-files "${_sysz_ls_args[@]}" '*@.*' |
-      cut -f1 -d' ' |
-      sed -e "s/^/[$mgr] /"
-  done
-
+  # show template files iff there are no other filters
+  if [[ $all_states = true && $all_types = true ]]; then
+    _sysz_ls list-unit-files '*@.*'
+  fi
 }
 
 # main
@@ -263,12 +286,12 @@ while [[ -n $1 ]]; do
     shift
     ;;
   -s | --state)
-    STATES+=("--state=$2")
+    STATES+=("$2")
     shift
     shift
     ;;
   --state=*)
-    STATES+=("$1")
+    STATES+=("${1#--state=}")
     shift
     ;;
   -v | --version)
@@ -288,13 +311,16 @@ while [[ -n $1 ]]; do
   esac
 done
 
-for STATE in "${STATES[@]}"; do
-  STATE="${STATE##*=}"
-  if [[ -n $STATE ]] && ! systemctl --state=help | grep -q "^${STATE}$"; then
-    echo "ERROR: Invalid state: $STATE" >&2
-    exit 1
-  fi
-done
+_sysz_check_states() {
+  for STATE in "${STATES[@]}"; do
+    if [[ -n $STATE ]] && ! systemctl --state=help | grep -q "^${STATE}$"; then
+      echo "ERROR: Invalid state: $STATE" >&2
+      exit 1
+    fi
+  done
+}
+
+_sysz_check_states
 
 declare CMD
 declare -a ARGS
@@ -387,7 +413,7 @@ _sysz_manager_prompt() {
     readarray -t MANAGERS || exit $?
 }
 
-_sysz_daemon_reload() {
+_sysz_daemon_reload_prompt() {
   (
     if [[ $EUID -ne 0 ]]; then
       echo '[user] daemon-reload'
@@ -412,26 +438,36 @@ _sysz_daemon_reload() {
   done
 }
 
-_sysz_states() {
+_sysz_states_prompt() {
+  local picked_states
   # hide 'ing' because they are transient states
   # which people probably aren't looking for
-  systemctl --state=help |
-    grep -v ':' |
-    grep -v 'ing' |
-    sort -u |
-    grep -v '^$' |
+  (
+    echo all
+    systemctl --state=help |
+      grep -v ':' |
+      grep -v 'ing' |
+      sort -u |
+      grep -v '^$'
+  ) |
     fzf \
       --multi \
       --prompt="States: " |
-    readarray -t PICKED_STATES || exit $?
+    readarray -t picked_states || exit $?
 
-  if [[ ${#PICKED_STATES[@]} -gt 0 ]]; then
+  if [[ ${#picked_states[@]} -eq 0 ]]; then
     STATES=()
+    return
   fi
 
-  for STATE in "${PICKED_STATES[@]}"; do
-    STATES+=("--state=$STATE")
+  for state in "${picked_states[@]}"; do
+    if [[ $state = all ]]; then
+      STATES=()
+      return
+    fi
+    STATES+=("$state")
   done
+  _sysz_check_states
 }
 
 while :; do
@@ -459,11 +495,11 @@ while :; do
 
   case $KEY in
   ctrl-r)
-    _sysz_daemon_reload
+    _sysz_daemon_reload_prompt
     continue
     ;;
   ctrl-s)
-    _sysz_states
+    _sysz_states_prompt
     continue
     ;;
   ctrl-x)
@@ -587,7 +623,7 @@ for PICK in "${UNITS[@]}"; do
       ;;
     status)
       # shellcheck disable=2086
-      SYSTEMD_COLORS=1 systemctl "$MANAGER" $CMD --no-pager "${ARGS[@]}" -- "$UNIT"
+      SYSTEMD_COLORS=1 _sysz_systemctl "$MANAGER" $CMD --no-pager "${ARGS[@]}" -- "$UNIT"
       ;;
     cat | show)
       _sysz_systemctl "$MANAGER" "$CMD" "${ARGS[@]}" -- "$UNIT" || exit $?
@@ -595,7 +631,7 @@ for PICK in "${UNITS[@]}"; do
     *)
       # shellcheck disable=2086
       _sysz_systemctl "$MANAGER" $CMD "${ARGS[@]}" -- "$UNIT" || CODE=$?
-      SYSTEMD_COLORS=1 systemctl "$MANAGER" status --no-pager -- "$UNIT"
+      SYSTEMD_COLORS=1 _sysz_systemctl "$MANAGER" status --no-pager -- "$UNIT"
       if [[ ${#UNITS[@]} -eq 1 ]]; then
         exit $CODE
       fi
