Add filtering by unit type

diff --git a/sysz b/sysz
--- a/sysz
+++ b/sysz
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 
+#set -x
 set -o pipefail
 shopt -s lastpipe
 shopt -s extglob
@@ -9,6 +10,10 @@ export SHELL=bash
 PROG=$(basename "$0")
 SYSZ_VERSION=1.4.3
 SYSZ_HISTORY=${SYSZ_HISTORY:-${XDG_CACHE_HOME:-~/.cache}/sysz/history}
+GREEN=$'\e[32m'
+YELLOW=$'\e[33m'
+RED=$'\e[31m'
+declare -a MANAGERS
 declare -a STATES
 declare -a TYPES
 
@@ -19,6 +24,7 @@ Keybindings:
   ctrl-r        Run daemon-reload. Selection is reset.
   ctrl-x        Switch between user or system managers. Selection is reset.
   ctrl-s        Select states to match. Selection is reset.
+  ctrl-t        Select types to match. Selection is reset.
   ctrl-v        'cat' the unit in the preview window.
   ctrl-p        History previous.
   ctrl-n        History next.
@@ -41,6 +47,7 @@ OPTS:
   -u, --user               Only show --user units
   --sys, --system          Only show --system units
   -s STATE, --state STATE  Only show units in STATE (repeatable)
+  -t TYPE, --type TYPE     Only show units of TYPE (repeatable)
   -V, --verbose            Print the systemctl command
   -v, --version            Print the version
   -h, --help               Print this message
@@ -74,17 +81,19 @@ Some units are colored based on state:
   yellow      not-found
 
 Examples:
-  $PROG -u                      User units
-  $PROG --sys -s active          Active system units
-  $PROG --user --state failed   Failed user units
+  $PROG -u                        User units
+  $PROG --sys -s active           Active system units
+  $PROG --user --state failed     Failed user units
+  $PROG --type socket             Sockets
+  $PROG -s inactive -t service    Inactive services
 
 Examples with commands:
-  $PROG start                  Start a unit
-  $PROG --sys s                Get the status of system units
-  $PROG --user edit            Edit user units
-  $PROG s -- -n100             Show status with 100 log lines
-  $PROG --sys -s active stop    Stop an active system unit
-  $PROG -u --state failed r    Restart failed user units
+  $PROG start                     Start a unit
+  $PROG --sys s                   Get the status of system units
+  $PROG --user edit               Edit user units
+  $PROG s -- -n100                Show status with 100 log lines
+  $PROG --sys -s active stop      Stop an active system unit
+  $PROG -u --state failed r       Restart failed user units
 EOF
 
   exit 0
@@ -150,7 +159,7 @@ _fzf_cat() {
 _fzf_preview() {
   local mgr
   local unit
-  IFS=" " read -r -a args <<< "$1"
+  IFS=" " read -r -a args <<<"$1"
   mgr=$(_sysz_manager "${args[0]}")
   unit=${args[1]}
 
@@ -171,89 +180,109 @@ _sysz_show() {
   _sysz_systemctl "$manager" show "$unit" -p "$2" --value
 }
 
-_sysz_ls_args=(
-  --legend=false
-  --full
-  --plain
-  --no-pager
-)
-
 _sysz_ls() {
-  local color_code
+  local color
   local state
-
-  for arg in "$@"; do
-    if [[ $arg = --state=* ]]; then
-      state=${arg#--state=} # strip --state=
-    fi
-  done
+  local filter
+  local reset
 
   reset=$'\e[0m'
+  color=$reset
+  filter=DO_NOT_MATCH
+  for arg in "$@"; do
+    case $arg in
+    --filter=*)
+      filter=${arg#--filter=} # strip --filter=
+      shift
+      ;;
+    --state=active)
+      color=$GREEN
+      ;;
+    --state=not-found)
+      color=$YELLOW
+      ;;
+    --state=failed)
+      color=$RED
+      ;;
+    esac
+  done
+
   case $state in
-  active)
-    color_code=$'\e[32m' # green
-    ;;
-  not-found)
-    color_code=$'\e[33m' # yellow
-    ;;
-  failed)
-    color_code=$'\e[31m' # red
-    ;;
-  *)
-    color_code=$reset
-    ;;
   esac
 
   for mgr in "${MANAGERS[@]}"; do
     _sysz_systemctl "--$mgr" \
-      "${_sysz_ls_args[@]}" \
+      --legend=false \
+      --full \
+      --plain \
+      --no-pager \
+      --all \
       "$@" |
-      cut -f1 -d' ' |
-      sed -e "s/^/$color_code/;s/\$/$reset/" |
+      grep -Ev '^\S+\s+(\S+\s+)?('"$filter"')' |
+      sed -e "s/^/$color/;s/\$/$reset/" |
       sed -e "s/^/[$mgr] /"
   done
 }
 
 _sysz_units() {
-  local all_states
-  local all_types
-  local types
-  local states
-  local cmds
-
-  cmds=(list-units list-unit-files)
-  states=("${STATES[@]}")
-  if [[ ${#STATES[@]} -eq 0 ]]; then
-    states=(failed active)
-    cmds=(list-units)
-    all_states=true
-  fi
-
-  types=("${TYPES[@]}")
-  if [[ ${#TYPES[@]} -eq 0 ]]; then
-    types=(service timer)
-    all_types=true
-  fi
-
-  for cmd in "${cmds[@]}"; do
-    for state in "${states[@]}"; do
-      for unit_type in "${types[@]}"; do
-        _sysz_ls "$cmd" "--state=$state" "--type=$unit_type"
+  if [[ ${#STATES[@]} -gt 0 && ${#TYPES[@]} -gt 0 ]]; then
+    for cmd in list-units list-unit-files; do
+      for state in "${STATES[@]}"; do
+        for unit_type in "${TYPES[@]}"; do
+          _sysz_ls "$cmd" "--state=$state" "--type=$unit_type"
+        done
       done
-
-      if [[ $all_types = true ]]; then
-        _sysz_ls "$cmd" "--state=$state" | grep -Ev '(\.service|\.timer)'
-      fi
     done
 
-    if [[ $all_states = true ]]; then
-      _sysz_ls "$cmd" --state=not-found
-      _sysz_ls "$cmd" --all | grep -Ev '( active| failed| not-found|\.service|\.timer)'
-    fi
-  done
+  elif [[ ${#STATES[@]} -gt 0 ]]; then
+    for cmd in list-units list-unit-files; do
+      for state in "${STATES[@]}"; do
+        for unit_type in service timer; do
+          _sysz_ls "$cmd" "--state=$state" "--type=$unit_type"
+        done
+        _sysz_ls "$cmd" "--state=$state" |
+          grep -Ev '^\[\S+\] \S+(\.service|\.timer)'
+      done
+    done
 
-  # show template files iff there are no other filters
-  if [[ $all_states = true && $all_types = true ]]; then
+  elif [[ ${#TYPES[@]} -gt 0 ]]; then
+    for unit_type in "${TYPES[@]}"; do
+      for state in failed active not-found; do
+        _sysz_ls list-units "--state=$state" "--type=$unit_type"
+      done
+      _sysz_ls "--filter=failed|active|not-found" list-units "--type=$unit_type"
+    done
+
+  else
+    # failed service
+    # failed timer
+    # failed units
+    # active service
+    # active timer
+    # active units
+    # not-found
+    # remaining service
+    # remaining timer
+    # remaining
+    # templates
+    for state in failed active; do
+      # show all failed and active services and timers first
+      _sysz_ls list-units "--state=$state" --type=service
+      _sysz_ls list-units "--state=$state" --type=timer
+      # show remaining failed and active units
+      _sysz_ls list-units "--state=$state" |
+        grep -Ev '^\[\S+\] \S+(\.service|\.timer)'
+    done
+    # show all not-found units
+    _sysz_ls list-units --state=not-found
+    # show remaining services
+    _sysz_ls '--filter=failed|active|not-found' list-units --type=service
+    # show remaining timers
+    _sysz_ls '--filter=failed|active|not-found' list-units --type=timer
+    # show all remaining units
+    _sysz_ls '--filter=failed|active|not-found' list-units |
+      grep -Ev '^\[\S+\] \S+(\.service|\.timer)'
+    # show all templates
     _sysz_ls list-unit-files '*@.*'
   fi
 }
@@ -295,6 +324,15 @@ while [[ -n $1 ]]; do
     STATES+=("${1#--state=}")
     shift
     ;;
+  -t | --type)
+    TYPES+=("$2")
+    shift
+    shift
+    ;;
+  --type=*)
+    TYPES+=("${1#--type=}")
+    shift
+    ;;
   -v | --version)
     echo "$PROG" $SYSZ_VERSION
     exit 0
@@ -313,15 +351,25 @@ while [[ -n $1 ]]; do
 done
 
 _sysz_check_states() {
-  for STATE in "${STATES[@]}"; do
-    if [[ -n $STATE ]] && ! systemctl --state=help | grep -q "^${STATE}$"; then
-      echo "ERROR: Invalid state: $STATE" >&2
+  for state in "${STATES[@]}"; do
+    if [[ -n $state ]] && ! systemctl --state=help | grep -v : | grep -q "^${state}$"; then
+      echo "ERROR: Invalid state: $state" >&2
+      exit 1
+    fi
+  done
+}
+
+_sysz_check_types() {
+  for unit_type in "${TYPES[@]}"; do
+    if [[ -n $unit_type ]] && ! systemctl --type=help | tail -n +2 | grep -q "^${unit_type}$"; then
+      echo "ERROR: Invalid type: $unit_type" >&2
       exit 1
     fi
   done
 }
 
 _sysz_check_states
+_sysz_check_types
 
 declare CMD
 declare -a ARGS
@@ -444,7 +492,7 @@ _sysz_states_prompt() {
   # hide 'ing' because they are transient states
   # which people probably aren't looking for
   (
-    echo all
+    echo '(all)'
     systemctl --state=help |
       grep -v ':' |
       grep -v 'ing' |
@@ -456,19 +504,44 @@ _sysz_states_prompt() {
       --prompt="States: " |
     readarray -t picked_states || exit $?
 
-  if [[ ${#picked_states[@]} -eq 0 ]]; then
-    STATES=()
-    return
-  fi
-
+  STATES=()
   for state in "${picked_states[@]}"; do
-    if [[ $state = all ]]; then
+    if [[ $state = '(all)' ]]; then
       STATES=()
       return
     fi
     STATES+=("$state")
   done
   _sysz_check_states
+}
+
+_sysz_types_prompt() {
+  local picked
+  (
+    echo '(all)'
+    echo service
+    echo timer
+    systemctl --type=help |
+      grep -v ':' |
+      grep -Ev '(service|timer)' |
+      sort -u |
+      grep -v '^$'
+  ) |
+    fzf \
+      --multi \
+      --no-sort \
+      --prompt="types: " |
+    readarray -t picked || exit $?
+
+  TYPES=()
+  for type in "${picked[@]}"; do
+    if [[ $type = '(all)' ]]; then
+      TYPES=()
+      return
+    fi
+    TYPES+=("$type")
+  done
+  _sysz_check_types
 }
 
 while :; do
@@ -480,14 +553,14 @@ while :; do
     fzf \
       --multi \
       --ansi \
-      --expect=ctrl-r,ctrl-s,ctrl-x \
+      --expect=ctrl-r,ctrl-s,ctrl-x,ctrl-t \
       --history="$SYSZ_HISTORY" \
       --prompt="Units: " \
       --header '? for keybindings' \
       --bind "?:preview(echo '$(_sysz_keys)')" \
       --bind "ctrl-v:preview('${BASH_SOURCE[0]}' _fzf_cat {})" \
       --preview="'${BASH_SOURCE[0]}' _fzf_preview {}" \
-      --preview-window=70% |
+      --preview-window=60% |
     readarray -t PICKS
 
   KEY=${PICKS[0]}
@@ -497,6 +570,10 @@ while :; do
   case $KEY in
   ctrl-r)
     _sysz_daemon_reload_prompt
+    continue
+    ;;
+  ctrl-t)
+    _sysz_types_prompt
     continue
     ;;
   ctrl-s)
@@ -554,6 +631,7 @@ else
     --multi \
     --ansi \
     --no-info \
+    --no-sort \
     --prompt="Commands: " \
     --preview="$PREVIEW_CMD" \
     --preview-window=80% < <(
